name: 'docker_airflow'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 5s
      retries: 5
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    deploy:
      resources:
        limits:
          cpus: '5'
          memory: 12G
        reservations:
          memory: 2G

  airflow-init:
    build:
      context: .
      dockerfile: Dockerfile.dockerfile
    image: apache/airflow:2.5.1
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__CORE__EXTRA_PACKAGES: "ijson pandas numpy matplotlib seaborn xgboost python-dotenv scikit-learn psycopg2-binary apache-airflow-providers-postgres sqlalchemy"
      PYTHONPATH: "/opt/airflow:/opt/airflow/dags:/opt/airflow/scripts"
      AIRFLOW__WEBSERVER__SECRET_KEY: "1234"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./plugins:/opt/airflow/plugins
      - ./data:/opt/airflow/data
      - ./scripts:/opt/airflow/scripts
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./requirements.txt:/requirements.txt
    command: >
      bash -c "
      airflow db init &&
      airflow users create --username airflow --password airflow --firstname Air --lastname Flow --role Admin --email admin@example.com
      "
#pip install -r /requirements.txt &&
    deploy:
      resources:
        limits:
          cpus: '6'
          memory: 12G

  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile.dockerfile
    image: apache/airflow:2.5.1
    depends_on:
      - postgres
      - airflow-init
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      PYTHONPATH: "/opt/airflow:/opt/airflow/dags:/opt/airflow/scripts"
      AIRFLOW__CORE__EXTRA_PACKAGES: "ijson pandas numpy matplotlib seaborn xgboost python-dotenv scikit-learn psycopg2-binary apache-airflow-providers-postgres sqlalchemy"
      AIRFLOW__WEBSERVER__SECRET_KEY: "1234"
      AIRFLOW__WEBSERVER__WORKER_REFRESH_MEMORY: "3072"
      AIRFLOW__WEBSERVER__WEB_SERVER_WORKER_TIMEOUT: "120"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./plugins:/opt/airflow/plugins
      - ./data:/opt/airflow/data
      - ./scripts:/opt/airflow/scripts
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "8080:8080"
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /opt/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '5'
          memory: 12G
        reservations:
          memory: 2G

  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile.dockerfile
    image: apache/airflow:2.5.1
    depends_on:
      - postgres
      - airflow-init
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      PYTHONPATH: "/opt/airflow:/opt/airflow/dags:/opt/airflow/scripts"
      AIRFLOW__CORE__EXTRA_PACKAGES: "ijson pandas numpy matplotlib seaborn xgboost python-dotenv scikit-learn psycopg2-binary apache-airflow-providers-postgres sqlalchemy"
      AIRFLOW__WEBSERVER__SECRET_KEY: "1234"
      AIRFLOW__SCHEDULER__SCHEDULER_HEARTBEAT_SEC: "10"
      AIRFLOW__SCHEDULER__MIN_FILE_PROCESS_INTERVAL: "30"
      AIRFLOW__SCHEDULER__PARSING_PROCESSES: "6"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./plugins:/opt/airflow/plugins
      - ./data:/opt/airflow/data
      - ./scripts:/opt/airflow/scripts
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    command: scheduler
    deploy:
      resources:
        limits:
          cpus: '5'
          memory: 12G
        reservations:
          memory: 2G

  airflow-worker:
    build:
      context: .
      dockerfile: Dockerfile.dockerfile
    image: apache/airflow:2.5.1
    depends_on:
      - postgres
      - airflow-init
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      PYTHONPATH: "/opt/airflow:/opt/airflow/dags:/opt/airflow/scripts"
      AIRFLOW__CORE__EXTRA_PACKAGES: "ijson pandas numpy matplotlib seaborn xgboost python-dotenv scikit-learn psycopg2-binary apache-airflow-providers-postgres sqlalchemy"
      AIRFLOW__WEBSERVER__SECRET_KEY: "1234"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./plugins:/opt/airflow/plugins
      - ./data:/opt/airflow/data
      - ./scripts:/opt/airflow/scripts
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    command: celery worker
    deploy:
      resources:
        limits:
          cpus: '5'
          memory: 12G
        reservations:
          memory: 2G

volumes:
  postgres_data: